version: '3.4'

services:
  frontend:
    build:
      context: ./frontend
      target: development
    command: yarn dev
    env_file:
      - .env
      - .env.local
    ports:
      - '3000:3000'
    volumes:
      - node_modules:/opt/secrets-frontend/node_modules
      - ./frontend:/opt/secrets-frontend:delegated

  backend: &backend
    build:
      context: ./backend
      target: development
    command: nodemon server.js
    env_file:
      - .env
    ports:
      - '8080:8080'

volumes:
  node_modules:
